environment: development

aws:
  region: us-east-1
  s3_bucket: jo-map
  s3_prefix: jo-map

snowflake:
  warehouse: MAP_WH
  database: MORTGAGE_ANALYTICS
  bronze_schema: BRONZE
  role: SYSADMIN

paths:
  data_root: data
  freddie_data: data/freddie_raw
  originations_data: data/freddie_raw/originations
  performance_data: data/freddie_raw/performance
  headers: data/headers
